# Site settings
title: liamness.co.uk
email: liam.p.duffy@gmail.com
description: all the liamness a liam could liam
url: 'https://liamness.co.uk/'
baseurl: ''
twitter_username: liamness
github_username: liamness

# Build settings
# Maybe don't need this?
keep_files: [
    bower_components,
    download,
    images,
    CNAME,
    style.css,
    favicon.ico,
    icons.svg,
    ga.html,
    googleca77a3c8b1ee82be.html
]
kramdown:
    auto_ids: false
markdown: kramdown
permalink: 'posts/:year/:month/:day/:title.html'
